"""Register our custom trainers into nnU-Net's trainer search path.

WHY THIS EXISTS
---------------
nnU-Net's trainer discovery (`recursive_find_python_class`) is hard-coded
to walk only one directory:
    <nnunetv2 install>/training/nnUNetTrainer/
If a trainer class isn't found there, nnU-Net errors out with
"Could not find requested nnunet trainer". Loading our trainers from
PYTHONPATH alone is NOT enough — we have to physically put them under
that path (or a subdirectory of it).

WHAT THIS DOES
--------------
Creates a subdirectory at:
    <nnunetv2 install>/training/nnUNetTrainer/variants/edain_register/
and symlinks every trainer file from our repo into it. nnU-Net's recursive
search then finds them by class name.

The trainer files reference our package via `Path(__file__).resolve()` which
follows the symlink back to the real repo location, so PYTHONPATH-based
imports (mri_edain_v1, mri_edain_v2, edain_nnunet) still work normally.

IDEMPOTENCY
-----------
Re-running is safe. Existing links are replaced. If `os.symlink` fails (Windows
without admin rights), we fall back to copying the file.

USAGE
-----
    python -m tools.register_trainers

Returns 0 on success. Prints what it did (or skipped).
"""
from __future__ import annotations
import os
import shutil
import sys
from pathlib import Path


def install(verbose: bool = True) -> Path:
    """Place symlinks in <nnunetv2>/training/nnUNetTrainer/variants/edain_register/.

    Returns:
        The target directory (where the trainers are now reachable).
    """
    try:
        import nnunetv2
    except ImportError as e:
        raise ImportError(
            "nnunetv2 is not installed. Run `pip install nnunetv2==2.7.0` first."
        ) from e

    nnunet_root = Path(nnunetv2.__path__[0])
    variants_dir = nnunet_root / "training" / "nnUNetTrainer" / "variants"
    target_dir = variants_dir / "edain_register"

    if not variants_dir.exists():
        raise FileNotFoundError(
            f"{variants_dir} does not exist. Did nnU-Net get installed correctly?"
        )

    target_dir.mkdir(parents=True, exist_ok=True)

    # Make the directory a package
    init_file = target_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text(
            "# auto-generated by tools/register_trainers.py\n"
            "# this package contains symlinks/copies of EDAIN+Nyul trainers\n"
        )
        if verbose:
            print(f"[register] created {init_file}")

    # Source trainer files in our repo
    repo_root = Path(__file__).resolve().parents[1]
    trainers_dir = repo_root / "edain_nnunet" / "trainers"
    if not trainers_dir.exists():
        raise FileNotFoundError(f"{trainers_dir} not found")

    candidates = sorted(trainers_dir.glob("nnUNetTrainer*.py"))
    if not candidates:
        raise FileNotFoundError(f"no trainer files in {trainers_dir}")

    for src in candidates:
        dst = target_dir / src.name
        # If dst already exists and points to the right place, skip
        if dst.is_symlink():
            try:
                if dst.resolve() == src.resolve():
                    if verbose:
                        print(f"[register] {dst.name}: link already up-to-date, skip")
                    continue
            except Exception:
                pass
            dst.unlink()
        elif dst.exists():
            # plain file with same content?
            if dst.read_bytes() == src.read_bytes():
                if verbose:
                    print(f"[register] {dst.name}: copy already up-to-date, skip")
                continue
            dst.unlink()
        # Try symlink first, fall back to copy.
        # FileExistsError can happen when 4 parallel sbatch jobs all hit this
        # at the same time — just skip if another process beat us to it.
        try:
            os.symlink(src, dst)
            if verbose:
                print(f"[register] symlink {dst} -> {src}")
        except FileExistsError:
            if verbose:
                print(f"[register] {dst.name}: appeared concurrently, skip")
        except OSError as e:
            try:
                shutil.copy2(src, dst)
                if verbose:
                    print(f"[register] copy {src} -> {dst}  ({e.strerror})")
            except FileExistsError:
                if verbose:
                    print(f"[register] {dst.name}: appeared concurrently, skip")

    if verbose:
        print(f"[register] DONE. Trainers reachable at:")
        print(f"            {target_dir}")
    return target_dir


def verify(trainer_names: list = None, verbose: bool = True) -> bool:
    """After install(), verify nnU-Net can discover each named trainer.

    Returns True iff all listed trainers resolve.
    """
    if trainer_names is None:
        trainer_names = [
            "nnUNetTrainerEDAINv1",
            "nnUNetTrainerEDAINv1Power",
            "nnUNetTrainerNyul",
            "nnUNetTrainerNyulIdentity",
            "nnUNetTrainerNyulPopnyul",
        ]
    import nnunetv2
    from batchgenerators.utilities.file_and_folder_operations import join
    from nnunetv2.utilities.find_class_by_name import recursive_find_python_class

    folder = join(nnunetv2.__path__[0], "training", "nnUNetTrainer")
    all_ok = True
    for name in trainer_names:
        cls = recursive_find_python_class(folder, name, "nnunetv2.training.nnUNetTrainer")
        ok = cls is not None
        if verbose:
            print(f"[verify] {name:<35s} {'OK' if ok else 'MISSING'}")
        all_ok = all_ok and ok
    return all_ok


def main():
    install(verbose=True)
    print()
    ok = verify(verbose=True)
    if not ok:
        sys.exit(1)
    print("\n[register] all trainers discoverable by nnU-Net.")


if __name__ == "__main__":
    main()
